version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "13:00"
  open-pull-requests-limit: 10
  reviewers:
  - Ericky14
  assignees:
  - Ericky14
  ignore:
  - dependency-name: html-webpack-plugin
    versions:
    - 4.5.1
  - dependency-name: urijs
    versions:
    - 1.19.5
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.3
  - dependency-name: enzyme-adapter-react-16
    versions:
    - 1.15.5
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: uuid
    versions:
    - 8.3.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
